import requests

def text_to_sql(natural_query: str) -> str:
    """
    Convert a natural language query into an SQL query using a locally running Ollama LLM.

    Args:
        natural_query (str): The natural language query provided by the user in app.py.

    Returns:
        str: The generated SQL query.

    Raises:
        Exception: If an error occurs during the API call or if no SQL query is returned.
    """
    # Ollama API endpoint URL.
    url = "http://localhost:11434/api/generate"  # Adjust the port if your setup differs.

    # Specify the model name as configured in your Ollama instance.
    model_name = "llama3"  # Replace with your actual model name if different.

    # Build the prompt for the LLM. It instructs the model to generate only the SQL query.
    prompt = (
        "You are an expert SQL generator. Convert the following natural language description into a valid SQL query. "
        "Only output the SQL query, without any additional text.\n\n"
        f"Natural Language Query: {natural_query}\n\n"
        "SQL Query:"
    )

    # Prepare the payload with the necessary parameters.
    payload = {
        "model": model_name,
        "prompt": prompt,
        "max_tokens": 150,
        "temperature": 0  # Lower temperature for more deterministic output.
    }

    try:
        # Send a POST request to the Ollama API.
        response = requests.post(url, json=payload)
        response.raise_for_status()  # Raises an HTTPError for bad responses.

        # Parse the JSON response.
        data = response.json()

        # Extract the SQL query from the response.
        sql_query = data.get("completion", "").strip()
        if not sql_query:
            raise ValueError("No SQL query was generated by the LLM.")
        return sql_query

    except Exception as e:
        raise Exception(f"Error converting text to SQL: {e}")

# Optional testing block.
if __name__ == "__main__":
    # This block allows you to test the function independently.
    sample_query = input("Enter a natural language query: ")
    try:
        sql_output = text_to_sql(sample_query)
        print("Generated SQL Query:")
        print(sql_output)
    except Exception as err:
        print("Error:", err)
